### ISSUE TITLE
last snapshot doesn't works lunch from icon

### ISSUE THREAD

**Issue by adallafontana** [MrKepzie/Natron#1464]
/Natron2/Natron' 
QFile::remove: Empty or null file name
Natron Version 2.1.5
Copyright (C) 2016 the Natron developers
>>>Use the --help or -h option to print usage.<<<

On linux ubuntu 16.04
if I try lunch Natron with icon or in the terminal with file ./Natron on Natron2 folder doesn't works.
if I lunch from executive Natron on bin folder works, but this operation is slow, I mean Natron start after some second.

**Comment by olear** [comment]
Yeah, the launch script was modified for some reason, will fix.

**Comment by olear** [comment]
It's not the script, for some reason "-style plastique" now stalls Natron.

**Comment by olear** [comment]
Fixed.

**Comment by adallafontana** [comment]
Natron-201610101249-683af488940e931a6a4f0a5ddcf34b0a5706c4b0-Linux-x86_64bit

still doesn't works

**Comment by olear** [comment]
It was fixed after that snapshot was released, next snapshot will have the fixes.
