### ISSUE TITLE
Writing EXR, then reading it in and writing out again fails in specific case

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1503]
### Problem
When following the process outlined in this report, Natron fails to render if project has an EXR file in it.

**Expected behavior:** 
Natron should render output file

**Actual behavior:** 
In the progress queue, the render claims to have finished but nothing is written. The process log includes the following error:

"Message(stdout): Persistent message: called OpenEXRInput::read_native_scanlines without an open file
Error(stderr): Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:/Program Files/INRIA/Natron-2.1.8/Plugins/PyPlugs/SplitAndJoin.py", line 6, in <module>
    from NatronGui import *
ImportError: No module named NatronGui
Error while rendering: Rendering Failed"

### Steps to Reproduce

1. Create a new Natron project.
2. In project settings, create a new format sized 3200x1800 and select that as the project format
3. Create SEnoise node
4. Connect SEnoise node to Write node, setting the frame range to manual, with starting frame and end frame set to "1". Set whatever filename you wish, as long as the output is EXR.
5. Render the Write node to disk.
6. Read the EXR file back into the project.
7. Add a Crop after the EXR read node, entering 1920 and 1080 under Size w and h respectively
8. Add a write node after the crop. Output file format or naming doesn't seem to matter.  Format settings do not seem to matter. Frame range doesn't seem to matter, though I had mine set to manual to write frame 1 only.
9. Render this newest Write node.

Natron will fail to render, although it reports rendering finished.

* **Natron version/commit** 
Natron 2.1.8 Release
* **OS version:** 
tested on Linux Mint 17 and Windows 7 Professional.

**Comment by rebuilder** [comment]
I'm finding I get this issue generally when loading EXR files written from Natron into a project with a format of 3200x1800. It doesn't seem to happen with EXRs from Blender. For example, reading an HD resolution EXR file, adding a transform that moves the contents a pixel outside the frame format, then cropping to frame format and trying to write out results in this issue.

An oddity that may be related is that if I've written a 2048x1152 mov file to disk as an EXR sequence, when I read that sequence in and connect it to the viewer in a project with a format larger than the sequence's format, the EXR's frame is shown as a dotted line and the projects format is seen as a box extending beyond the EXR's bounds. This does not occur with EXRs from Blender.

**Comment by MrKepzie** [comment]
EXR has 2 distinct boxes: data window and display window. The data window is where pixels are defined. The display window is an indication on what pixels should be visible. Typically this is used for filtering to get extra pixels on the edges. 
In Natron the data window is represented by the dotted line whereas the format (or display window) is displayed plain.
Blender probably does not make a distinction of the 2 boxes and exports data winwdow = display window.
In Natron you may do the same if you crop your content to the format before writing out.

**Comment by rebuilder** [comment]
I tried cropping the SEnoise in my example before writing it out, this does not help the issue.

I took a look with exiftool at a file from Blender that I can render out, it has the same values for Data Window and Display Window. But so does the problematic file from Natron.

The most obvious difference I can see is that Blender writes EXRs with "Layout Scan lines" while Natron uses "Layout Tiles".

**Comment by MrKepzie** [comment]
This is a small bug in the plug-in indeed, it seems we try to read scan-lines even if the file is tiled. I'll fix that for 2.1.9. In the meantime set the "Tile Size" to Untiled and it will work fine.

**Comment by MrKepzie** [comment]
Note that tile files are generally much more efficient to read for any software (except Nuke), so try exporting tiles if you can.

**Comment by rebuilder** [comment]
Thank you, Tile Size Untitled fixes it. This was actually giving me quite a bit of trouble as I needed to precomp some things...

**Comment by MrKepzie** [comment]
Ok I fixed it. I launched a snapshot build, it will be available in a few hours, can you try on the new version if this fixes it ?

**Comment by rebuilder** [comment]
Tested with 2.1.9 snapshot, recreated the script as described, same issue still persists.

**Comment by MrKepzie** [comment]
Hmm I'm able to reproduce the steps in the original topic without any issue. Please provide steps (or video) to reproduce it

**Comment by rebuilder** [comment]
So you can reproduce the issue? In case I misunderstood,  here's a screencast anyway.
https://sendvid.com/kov2c8vo

**Comment by MrKepzie** [comment]
It seems you don't have the fixed version actually

**Comment by MrKepzie** [comment]
by default now the write node is set to Untiled, I see you have it on Tile Size: 256

**Comment by rebuilder** [comment]
Ok. This snapshot was downloaded on November 18th.

**Comment by MrKepzie** [comment]
There's one from yesterday, can you try that one out ?

**Comment by rebuilder** [comment]
I downloaded the new snapshot, the tile size still defaults to 256 on the EXR writer. Is it possible some setting has been saved by a previous version that is getting loaded to cause this?

**Comment by MrKepzie** [comment]
can you show me the about window commit hashes ?

**Comment by rebuilder** [comment]
These?:
This software was compiled from the source code branch RB-2.1 at version 9e95ea9 using GNU C++ version 4.8.5 with OpenMP 201107 targetting Intel x86-64 for Linux.
The bundled openfx-io plugins were compiled from version 364f3ce.
The bundled openfx-misc plugins were compiled from version df334cd.
The bundled openfx-arena plugins were compiled from version c34281a.

**Comment by MrKepzie** [comment]
Yes, the version is correct. On the same version I am able to reproduce the steps fine. Do you have a init.py script somewhere ?

**Comment by rebuilder** [comment]
I had an old init.py under ~/.Natron which contained an attempt to turn the default unpremult/premult of grade nodes off:
import NatronEngine
def afterNodeCreatedCallback(thisNode, app, userEdited):
    
    #Turn-off the Clamp black for new grade nodes
    if thisNode.getPluginID() == "net.sf.openfx.GradePlugin":
        thisNode.unPremult.setDefaultValue(False)


This doesn't seem relevant, also I don't think it's being loaded to begin with, and I tried creating a new write node after removing this file, no change in behaviour.

**Comment by MrKepzie** [comment]
Are you sure the plug-ins your are loading are the one bundled with Natron ? Please check your Preferences/Plugin tab

**Comment by rebuilder** [comment]
I removed all plugins I had loaded from preferences, no change. I had Channelmath and Ink under OFXplugins and the community pyplugs in pyplugs.

If it helps, the ID for the plugin for WriteExr is listed as fr.inria.openfx.WriteEXR , version shown as 1.0

**Comment by olear** [comment]
The latest snapshot defaults to Tile Size 256, if I use a devel build from RB-2.1 it's Untiled.

**Comment by olear** [comment]
openfx-io on Linux and Windows was not updated due to a bug I introduced in the build system yesterday, a new snapshot will be made available in about an hour.
