### ISSUE TITLE
Reformat settings break after PyPlug export

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1749]
### Problem

I used Reformats in a PyPlug, set to "scale". When I export the PyPlug, "scale" is still selected but you can't see the scale-slider, only the format-dropdown. Further, it reformats not to the set format from the dropdown, but to the res the PyPlug was build upon.

For better understanding, see here: https://youtu.be/PkZ6OtZ-5pA

**Expected behavior:**
Reformats should keep their settings after PyPlug exports

**Actual behavior:**
Reformats break from their usual behaviour and set weird settings after PyPlug export

### Steps to Reproduce

1. Create a Checkerboard at 720p resolution
2. Create a Reformat and connect it to the Checkerbaord
3. Change the type to "scale", set it to 0.5
4. Put the Reformat inside a group
5. Export the Group as PyPlug
6. Make a new script and create a Checkerboard at 1080p resolution
7. Load the PyPlug
8. Check the setup and formats you get

### Versions

* **Natron version/commit** 2.3.10 (snapshot, 31032018)
* **OS version:** Windows 10 Professional

**Comment by devernay** [comment]
should be fixed in next snapshot, reopen if not

**Comment by CameraRick** [comment]
It seems I can't re-open issues here, so I will just comment

I tried, and while the settings inside the PyPlug appear to be correct (Scale, set to 0.1), the result is still wrong (0.1 of the original resolution)
Switching to format and back to scale solves the issue just like before

**Comment by devernay** [comment]
please try next snapshot

**Comment by CameraRick** [comment]
Works now. Thank you again :)
