### ISSUE TITLE
No Read or Write Plugins with Natron x64

### ISSUE THREAD

**Issue by InRoCh** [MrKepzie/Natron#745]
Since Natron-47f863dfa03c8abbf0ff3b0b6fed4b5f60b70c3d,
i can't open any Still or Sequence on Windows x64 but there is no problems with x86.

**Comment by MrKepzie** [comment]
30 minutes ago I updated the ffmpeg binaries which should resolve the issue. Please confirm that the next snapshot that will be uploaded has the readers/writers back

**Comment by ChristoError** [comment]
Le 10/07/2015 19:45, Alexandre Gauthier a écrit :
>
> 30 minutes ago I updated the ffmpeg binaries which should resolve the 
> issue. Please confirm that the next snapshot that will be uploaded has 
> the readers/writers back
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MrKepzie/Natron/issues/745#issuecomment-120491686>.
>
I try the x64 Natron-5468ea8784e0003836072595994022cc21237d85 version 
but it's not fixed.
By the way i didn't noticed before but the Text plugin isn't there either.
I've attached a screenshot of the "Preferences Tab" where you can't see 
Readers or Writers Tab.
here is the paste of the error log when i open this file 
http://photon.works/mantissa/mantissa_natron101_files.zip:


ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.ReadOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

ERROR: The node fr.inria.openfx.WriteOIIO version 1.0 was found in the 
script but does not exist in the loaded plug-ins.

Merge1: Could not find a parameter named Output_channels

Merge2: Could not find a parameter named Output_channels

Merge3: Could not find a parameter named Output_channels

Merge4: Could not find a parameter named Output_channels

Merge5: Could not find a parameter named Output_channels

Grade1: Could not find a parameter named Output_channels

BlurCImg1: Could not find a parameter named Output_channels

Grade2: Could not find a parameter named Output_channels

Grade5: Could not find a parameter named Output_channels

Grade6: Could not find a parameter named Output_channels

Radial1: Could not find a parameter named Output_channels

Roto1: Could not find a parameter named Output_channels

Grade3: Could not find a parameter named Output_channels

Radial2: Could not find a parameter named Output_channels

Merge6: Could not find a parameter named Output_channels

BlurCImg2: Could not find a parameter named Output_channels

Merge7: Could not find a parameter named Output_channels

Grade4: Could not find a parameter named Output_channels

**Comment by MrKepzie** [comment]
There was still a bug with the ffmpeg build, I recompiled it. However I cannot update the binaries on the build server so I'm uploading the new build manually up on source forge, I'll give you a link when it's done.

**Comment by MrKepzie** [comment]
Here is the download link, please try it out https://sourceforge.net/projects/natron/files/Natron-5468ea8784e0003836072595994022cc21237d85.zip/download

**Comment by ChristoError** [comment]
Sorry MK but this still don't do it
I've got the same error log like before.
I send you another screenshot of the first "Toolbar Button" where readers/writers missing.
![first_tool_button](https://cloud.githubusercontent.com/assets/13278672/8633652/47f58df6-27cb-11e5-9e5d-7257eababec0.png)

**Comment by ChristoError** [comment]
I forgot to tell you that the last snapshot build that works was
Natron-47f863dfa03c8abbf0ff3b0b6fed4b5f60b70c3d witch was published the 25/06/2015.

**Comment by MrKepzie** [comment]
That is still due to a wrong ffmpeg version, I will try and see whats wrong

**Comment by ReverendVodka** [comment]
I just got the newest version of Natron (v1.2.1) to see if the issue of it crashing when saving was resolved and now it crashes when trying to use the Read node so I do not know if the original problem was solved.  Thanks for looking into this.

**Comment by MrKepzie** [comment]
The crash you have is this issue, please refer to it: https://github.com/MrKepzie/Natron/issues/413

**Comment by MrKepzie** [comment]
I've uploaded a new version right here which should work now: https://sourceforge.net/projects/natron/files/Natron_Win64_2873e2e351fb2cbd2f338d0915a55dd7346a3fa0.zip/download

I will update build server tomorrow with the fixes for ffmpeg

**Comment by InRoCh** [comment]
Well done,  Success !!!
Reads and Writes works fine again
                                                           and "Vive la France".
