### ISSUE TITLE
Natron crash if shuffle is connect to multilayer exr

### ISSUE THREAD

**Issue by gitwipo** [MrKepzie/Natron#961]
Natrom crashes when you connect an Input to the exr file reader. The file is 18M big and has 49 image planes.

> terminal output:
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script not loaded
initGui.py script not loaded
./Natron: line 87: 29052 Segmentation fault      (core dumped) "$DIR/bin/Natron" -style fusion "$@"

System: 
Centos 7 - 3.10.0-229.4.2.el7.x86_64
Gnome 3.8.4
Nvidia driver version 346.59

**Comment by MrKepzie** [comment]
This has been solved in a recent commit, on this issue https://github.com/MrKepzie/Natron/issues/957.
Please confirm with a recent snapshot that this is fixed:

http://downloads.natron.fr/Linux/snapshots/64bit/files/

**Comment by gitwipo** [comment]
The problem still exits.
Tried Natron-68211e1c83ad65fa648ec4a048abe81a83b7833f-Linux-x86_64bit

Still get:

[ARXANIMA\wilfried@cw006 Natron2_snapshot]$ ./Natron
Natron Version 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<
init.py script not loaded
initGui.py script not loaded
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Permission denied
QFileSystemWatcher: failed to add paths: /root
./Natron: line 87: 31027 Segmentation fault      (core dumped) "$DIR/bin/Natron" -style fusion "$@"

**Comment by MrKepzie** [comment]
Can you post a screen recording on how to reproduce the bug ? Or any relevant files so I can reproduce it

**Comment by gitwipo** [comment]
https://github.com/gitwipo/uploades/blob/master/houdini_multilayer_exr_natron_crash.exr.txt

Please remove '.txt' from the file. You should be able to recreate the if you load the file and connect an shuffle and viewer.

**Comment by MrKepzie** [comment]
This has been fixed in RC2
