### ISSUE TITLE
Multilayered EXR - matte ID pass is not read by Natron

### ISSUE THREAD

**Issue by sirdavid32** [MrKepzie/Natron#965]
Good day. I´ve tried to create new channels in natron to "shuffle in" information about Matte ID pass that I am generating from modo (as shown in the picture) when I go to Natron, I don´t see the Matte ID pass (this was visible and working on snapshots previous to Natron RC v2).

![passesmodo](https://cloud.githubusercontent.com/assets/11066585/10521702/f2f91e0a-7336-11e5-9cac-8896f95064c7.jpg)

Focusing on the matte ID pass:
![id](https://cloud.githubusercontent.com/assets/11066585/10521728/055a49f2-7337-11e5-906f-13fa51b8b497.png)

And this is all NATRON sees on the .exr file:
![nat-no-pass](https://cloud.githubusercontent.com/assets/11066585/10521796/48aee848-7337-11e5-8aaa-f15920f10e1b.jpg)

**Comment by zabander** [comment]
Confirmed. It doesn't work. Modo uses open exr 2.x

**Comment by MrKepzie** [comment]
Was fixed in https://github.com/MrKepzie/Natron/issues/962

**Comment by sirdavid32** [comment]
Today´s snapshot still doesn´t recognize the extra passes. How´s this closed? (I´m just asking, not to be rude).

**Comment by MrKepzie** [comment]
Which platform ? Send us a sample exr to reproduce the bug please

**Comment by zabander** [comment]
@MrKepzie, I'm currently using windows 7 and there hasn't been an update or new snapshot since Oct 14 before the bug were fixed. So my current version is not fixed yet.

**Comment by zabander** [comment]
Is there any new snapshot for windows? Only linux has been updated since Oct 14 Thanks!

**Comment by MrKepzie** [comment]
Ok will investigate the snapshots)

**Comment by MrKepzie** [comment]
Anyway the issue is fixed and the snapshots will be back online soon.

**Comment by zabander** [comment]
Thank you @MrKepzie!!
